#!/bin/bash
#SBATCH --nodes=4
#SBATCH --ntasks-per-node=16
#SBATCH --time=04:00:00
#SBATCH --job-name=htseq_counter

sbatch htseq_N052611_Dex
sbatch htseq_N052611_untreated
sbatch htseq_N080611_Dex
sbatch htseq_N080611_untreated
sbatch htseq_N61311_Dex
sbatch htseq_N61311_untreated
