#!/bin/bash
#SBATCH --nodes=4
#SBATCH --ntasks-per-node=16
#SBATCH --time=04:00:00

module load anaconda3/5.2.0 htseq/0.11.1

htseq-count --format bam --order name --mode intersection-strict --stranded reverse --minaqual 1 --type exon --idattr gene_id /scratch/l/lcl_uotmmg3003/lcl_uotmmg3003s2058/AIRWAY_HISAT2_ALIGNMENTS/N61311_Dex.bam /scratch/l/lcl_uotmmg3003/lcl_uotmmg3003s2058/RNA_REF_DIR/Homo_sapiens.GRCh38.86.gtf > N61311_Dex.tsv
